Models/Bowler.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission13.Models
{
    public class Bowler
    {
        [Key]
        [Required]
        public int BowlerID { get; set; } 
        public string BowlerLastName { get; set; }
        public string BowlerFirstName { get; set; }
        public string BowlerMiddleInit { get; set; }
        public string BowlerAddress { get; set; }
        public string BowlerCity { get; set; }
        public string BowlerState { get; set; }
        public string BowlerZip { get; set; }
        public string BowlerPhoneNumber { get; set; }
        public int TeamID { get; set; }
    }
}

Models/BowlingDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission13.Models
{
    public class BowlingDbContext : DbContext
    {
        public BowlingDbContext(DbContextOptions<BowlingDbContext> options) : base(options)
        {

        }

        public DbSet<Bowler> Bowlers { get; set; }
        public DbSet<Team> Teams { get; set; }
    }
}

Models/EFBowlersRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission13.Models
{
    public class EFBowlersRepository : IBowlersRepository
    {
        private BowlingDbContext _context { get; set; }
        public EFBowlersRepository (BowlingDbContext temp)
        {
            _context = temp;
        }
        public IQueryable<Bowler> Bowlers => _context.Bowlers;

        public void CreateBowler(Bowler b)
        {
            _context.Add(b);
            _context.SaveChanges();
        }

        public void Update(Bowler b)
        {
            _context.SaveChanges();
        }

        public void DeleteBowler (Bowler b)
        {
            _context.Remove(b);
            _context.SaveChanges();
        }

        public void SaveChanges(Bowler b)
        {
            _context.SaveChanges();
        }

    }
}

Models/IBowlersRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission13.Models
{
    public interface IBowlersRepository
    {
        IQueryable<Bowler> Bowlers { get; }

        public void CreateBowler(Bowler b);
        public void Update(Bowler b);
        public void DeleteBowler(Bowler b);
        public void SaveChanges(Bowler b);
    }
}

Models/Team.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission13.Models
{
    public class Team
    {
        [Key]
        [Required]
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public int CaptainID { get; set; }


    }
}

Components/TeamsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission13.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission13.Components
{
    public class TeamsViewComponent : ViewComponent
    {
        private BowlingDbContext _context { get; set; }

        public TeamsViewComponent(BowlingDbContext temp)
        {
            _context = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedTeam = RouteData?.Values["teamname"];

            var teams = _context.Teams
                //.Select(x => x.TeamName)
                .Distinct()
                .OrderBy(x => x);

            return View(teams);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Mission13.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Mission13.Controllers
{
    public class HomeController : Controller
    {
        private BowlingDbContext _context { get; set; }

        //Constructor
        public HomeController(BowlingDbContext temp)
        {
            _context = temp;
        }

        public IActionResult Index(int teamid)
        {
            var bowling = _context.Bowlers
                .Where(b => b.TeamID == teamid || teamid == 0)
                .ToList();
            if (teamid == 0)
            {
                ViewBag.Header = "All Teams";
            }
            else
            {
                ViewBag.Header = _context.Teams.Single(x => x.TeamID == teamid).TeamName;
            }

            var blah = _context.Bowlers
                //.FromSqlRaw("SELECT * FROM bowlers WHERE BowlerFirstName = 'Barbara'")
                .Where(b => b.TeamID == teamid || teamid == 0)
                .ToList();

            return View(bowling);
        }

        [HttpGet]
        public IActionResult AddBowler()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddBowler(Bowler b)
        {
            _context.Add(b);
            _context.SaveChanges();
            //return View("Index");
            return RedirectToAction("Index", b);
        }

        [HttpGet]
        public IActionResult Edit(int BowlerID)
        {
            ViewBag.Bowler = _context.Bowlers.ToList();
            var bowler = _context.Bowlers.Single(b => b.BowlerID == BowlerID);

            return View("Edit", bowler);
        }

        [HttpPost]
        public IActionResult Edit(Bowler b)
        {
            _context.Update(b);
            _context.SaveChanges();

            return RedirectToAction("Index", b);
            
        }

        [HttpGet]
        public IActionResult DeleteConfirmation(int bowlerid)
        {
            var bowler = _context.Bowlers.Single(x => x.BowlerID == bowlerid);

            return View();
        }

        [HttpPost]
        public IActionResult DeleteConfirmation(Bowler bowler)
        {
            _context.Bowlers.Where(b => b.BowlerID == bowler.BowlerID);

            _context.Bowlers.Remove(bowler);
            _context.SaveChanges();

            return RedirectToAction("Index");
            //return View("Index");

        }

    }
}

Views/Home/AddBowler.cshtml
@{
    ViewData["Title"] = "Add Bowler";
}

@model Mission13.Models.Bowler

<h1 class="display-4">Add a Bowler</h1>

<form method="post">
    <div class="form__div">
        <label class="form__label" asp-for="BowlerFirstName">First Name:</label>
        <input class="form__input" placeholder=" " asp-for="BowlerFirstName" />
    </div>
    <div class="form__div">
        <label class="form__label" asp-for="BowlerMiddleInit">Middle Initial:</label>
        <input class="form__input" placeholder=" " asp-for="BowlerMiddleInit" maxlength="1"/>
    </div>
    <div class="form__div">
        <label class="form__label" asp-for="BowlerLastName">Last Name:</label>
        <input class="form__input" placeholder=" " asp-for="BowlerLastName" />
    </div>
    <div class="form__div">
        <label class="form__label" asp-for="BowlerAddress">Address:</label>
        <input class="form__input" placeholder=" " asp-for="BowlerAddress" />
    </div>
    <div class="form__div">
        <label class="form__label" asp-for="BowlerCity">City:</label>
        <input class="form__input" placeholder=" " asp-for="BowlerCity" />
    </div>
    <div class="form__div">
        <label class="form__label" asp-for="BowlerState">State:</label>
        <input class="form__input" placeholder=" " asp-for="BowlerState" />
    </div>
    <div class="form__div">
        <label class="form__label" asp-for="BowlerZip">Zip:</label>
        <input class="form__input" placeholder=" " asp-for="BowlerZip" />
    </div>
    <div class="form__div">
        <label class="form__label" asp-for="BowlerPhoneNumber">Phone Number:</label>
        <input class="form__input" placeholder=" " asp-for="BowlerPhoneNumber" />
    </div>
    <div class="form__div">
        <label class="form__label" asp-for="TeamID">Team ID:</label>
        <input class="form__input" placeholder=" " asp-for="TeamID" />
    </div>

    <button type="submit">Submit</button>

</form>

Views/Home/DeleteConfirmation.cshtml
@{
    ViewData["Title"] = "Delete Bowler";
}

@model Bowler

<h1 class="display-4">Are you sure you want to delete?</h1>

<form method="post" asp-controller="Home" asp-action="DeleteConfirmation">
    <button type="submit">Delete</button>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Cancel</a>

    <input type="hidden" asp-for="BowlerID" />
</form>

Views/Home/Edit.cshtml
@{
    ViewData["Title"] = "Edit Bowler";
}

@model Mission13.Models.Bowler

<h1 class="display-4">Add a Bowler</h1>

<form method="post">
    <div class="form__div">
        <label class="form__label" asp-for="BowlerFirstName">First Name:</label>
        <input class="form__input" placeholder=" " asp-for="BowlerFirstName" />
    </div>
    <div class="form__div">
        <label class="form__label" asp-for="BowlerMiddleInit">Middle Initial:</label>
        <input class="form__input" placeholder=" " asp-for="BowlerMiddleInit"maxlength="1" />
    </div>
    <div class="form__div">
        <label class="form__label" asp-for="BowlerLastName">Last Name:</label>
        <input class="form__input" placeholder=" " asp-for="BowlerLastName" />
    </div>
    <div class="form__div">
        <label class="form__label" asp-for="BowlerAddress">Address:</label>
        <input class="form__input" placeholder=" " asp-for="BowlerAddress" />
    </div>
    <div class="form__div">
        <label class="form__label" asp-for="BowlerCity">City:</label>
        <input class="form__input" placeholder=" " asp-for="BowlerCity" />
    </div>
    <div class="form__div">
        <label class="form__label" asp-for="BowlerState">State:</label>
        <input class="form__input" placeholder=" " asp-for="BowlerState" />
    </div>
    <div class="form__div">
        <label class="form__label" asp-for="BowlerZip">Zip:</label>
        <input class="form__input" placeholder=" " asp-for="BowlerZip" />
    </div>
    <div class="form__div">
        <label class="form__label" asp-for="BowlerPhoneNumber">Phone Number:</label>
        <input class="form__input" placeholder=" " asp-for="BowlerPhoneNumber" />
    </div>
    <div class="form__div">
        <label class="form__label" asp-for="TeamID">Team ID:</label>
        <input class="form__input" placeholder=" " asp-for="TeamID" />
    </div>

    <button type="submit">Submit</button>

</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model List<Bowler>
@*@model Mission13.Models.Team*@
@*@model Mission13.Models.Bowler*@

<h1 style="text-align: center;">Bowlers</h1>
<h3>@ViewBag.Header</h3>

<div class="row m-1 p-1">

    <div id="teams" class="col-2">
        <vc:teams></vc:teams>
    </div>

    <div class="col-10">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <td><b>ID</b></td>
                    <td><b>First Name</b></td>
                    <td><b>Middle Initial</b></td>
                    <td><b>Last Name</b></td>
                    <td><b>Address</b></td>
                    <td><b>City</b></td>
                    <td><b>State</b></td>
                    <td><b>Zip</b></td>
                    <td><b>Phone Number</b></td>
                    <td><b>Team ID</b></td>
                    <td><b>Edit</b></td>
                    <td><b>Delete</b></td>

                </tr>
            </thead>

            <tbody>
                @foreach (Bowler b in Model)
                {
                    <tr>
                        <td>@b.BowlerID</td>
                        <td>@b.BowlerFirstName</td>
                        <td>@b.BowlerMiddleInit</td>
                        <td>@b.BowlerLastName</td>
                        <td>@b.BowlerAddress</td>
                        <td>@b.BowlerCity</td>
                        <td>@b.BowlerState</td>
                        <td>@b.BowlerZip</td>
                        <td>@b.BowlerPhoneNumber</td>
                        <td>@b.TeamID</td>

                        <td>
                            <a asp-controller="Home" asp-action="Edit" asp-route-bowlerid="@b.BowlerID"
                               class="btn btn-warning btn-sm">Edit</a>
                        </td>
                        <td>
                            <a asp-controller="Home" asp-action="DeleteConfirmation" asp-route-bowlerid="@b.BowlerID"
                               class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Shared/Components/Teams/Default.cshtml
@{
}
@model IEnumerable<Team>

<a asp-controller="Home" asp-action="Index" asp-route-teamid="" asp-route-teamname=""
   class="btn btn-outline-secondary" style="width:120px;">Home</a>

@foreach(Team t in Model)
{
    <a asp-controller="Home" asp-action="Index" asp-route-teamid="@t.TeamID" asp-route-teamname="@t.TeamName" 
       class="btn @(ViewBag.SelectedTeam == t.TeamName ? "btn-primary" : "btn-outline-secondary")"
       style="margin-top: 7px; margin-right: 4px; width:120px;">@t.TeamName</a><br />
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mission13</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mission13</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AddBowler">Add Bowler</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div>
            @RenderBody()
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Mission13 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>